#!/usr/bin/env bash

LATEST_VERSION="7"

if [ "$DOCKER_TAG" = "latest" ]; then
	POSTMANVERSION=$LATEST_VERSION
else
	POSTMANVERSION=$DOCKER_TAG
fi

if [ "$POSTMANVERSION" = "7" ]; then
	VERSION=7.2.2
	FILE_SHA256SUM=9810b4de280e0c7107eb5b0a5ef29e6c7c93d4f807426f14b165f83a413307e2
elif [ "$POSTMANVERSION" = "6" ]; then
	VERSION=6.7.4
	FILE_SHA256SUM=985e1fd9af6f9cfacb935f9e7705e4725bdc6fd7caa8d52c95f86a5011df847f
else
	echo "Need to specify base image"
	exit 1
fi

docker build -t ${IMAGE_NAME} \
	--build-arg=VERSION=$VERSION \
	--build-arg=FILE_SHA256SUM=$FILE_SHA256SUM \
	--build-arg=DOCKER_TAG=$DOCKER_TAG \
	.
